
// This helper now requires DB access, but `t` is usually synchronous in React.
// Strategy: Load language into memory on App start, or rely on a context.
// For simplicity in this demo, we will check localStorage for basic settings (fast)
// but DB for authoritative settings.

const translations: Record<string, Record<string, string>> = {
  en: {
    // ... existing English translations ...
    'nav.dashboard': 'Dashboard',
    'nav.sales_group': 'Sales',
    'nav.new_invoice': 'New Invoice',
    'nav.invoices': 'Sales Log',
    'nav.purchases_group': 'Purchases',
    'nav.new_purchase': 'New Purchase',
    'nav.purchase_log': 'Purchase Log',
    'nav.inventory': 'Inventory',
    'nav.customers': 'Customers',
    'nav.suppliers': 'Suppliers',
    'nav.representatives': 'Representatives',
    'nav.warehouses': 'Warehouses',
    'nav.deals': 'Deals',
    'nav.cash': 'Cash Register',
    'nav.settings': 'Settings',
    'nav.reports': 'Reports & Analytics',
    'nav.reports_sales': 'Sales Reports',
    'nav.reports_purchases': 'Purchase Reports',
    'nav.reports_reps': 'Representatives Reports',
    'app.name': 'Mizan Online',
    'app.admin': 'Administrator',
    'app.overview': 'Overview',
    'dash.total_sales': 'Total Sales',
    'dash.cash_balance': 'Cash Balance',
    'dash.customers': 'Customers',
    'dash.low_stock': 'Low Stock',
    'dash.sales_trend': 'Sales Trend (7 Days)',
    'dash.inventory_health': 'Inventory Health',
    'stock.title': 'Inventory Management',
    'stock.import': 'Import Excel',
    'stock.new': '+ Quick Item',
    'stock.purchase': 'Purchase Invoice',
    'stock.return': 'Return Invoice',
    'stock.total': 'Total Stock',
    'stock.batch': 'Batch',
    'stock.expiry': 'Expiry',
    'stock.price': 'Price',
    'stock.cost': 'Cost',
    'stock.qty': 'Qty',
    'stock.active': 'ACTIVE',
    'stock.expired': 'EXPIRED',
    'stock.warehouse': 'Warehouse',
    'stock.transfer': 'Transfer Stock',
    'stock.transfer_title': 'Transfer Between Warehouses',
    'stock.to_warehouse': 'To Warehouse',
    'stock.transfer_qty': 'Transfer Qty',
    'ware.title': 'Warehouse Management',
    'ware.add': 'Add Warehouse',
    'ware.name': 'Warehouse Name',
    'ware.type': 'Type',
    'ware.default': 'Main Store',
    'ware.sub': 'Sub Store',
    'cust.title': 'Customers',
    'cust.add': 'Add Customer',
    'cust.search': 'Search...',
    'cust.code': 'Code',
    'cust.name': 'Name',
    'cust.phone': 'Phone',
    'cust.balance': 'Balance',
    'cust.rep': 'Representative',
    'supp.title': 'Suppliers',
    'supp.add': 'Add Supplier',
    'supp.contact': 'Contact Person',
    'rep.title': 'Sales Representatives',
    'rep.add': 'Add Rep',
    'rep.code': 'Rep Code',
    'rep.name': 'Rep Name',
    'rep.customers_count': 'Assigned Customers',
    'cash.title': 'Cash Register',
    'cash.receipt': 'Receipt',
    'cash.expense': 'Expense',
    'cash.history': 'History',
    'cash.category': 'Category',
    'cash.entity': 'Account/Name',
    'cash.income': 'Total Income',
    'cash.total_expenses': 'Total Expenses',
    'cash.net': 'Net Cash',
    'cat.CUSTOMER_PAYMENT': 'Customer Payment',
    'cat.PARTNER_CONTRIBUTION': 'Partner Contribution',
    'cat.SUPPLIER_PAYMENT': 'Supplier Payment',
    'cat.SALARY': 'Salaries',
    'cat.ELECTRICITY': 'Electricity',
    'cat.MARKETING': 'Marketing',
    'cat.DOCTOR_COMMISSION': 'Doctor Commission',
    'cat.OTHER': 'Other',
    'deal.title': 'Deals & Commissions',
    'deal.add': 'New Deal',
    'deal.edit': 'Edit Deal',
    'deal.save': 'Save Deal',
    'deal.update': 'Update Deal',
    'deal.doctor': 'Doctor Name',
    'deal.linked_cust': 'Linked Pharmacies',
    'deal.pay_comm': 'Pay Commission',
    'deal.sales_vol': 'Deal Volume',
    'deal.select_cust': 'Select Customers',
    'deal.amount': 'Initial Amount (Optional)',
    'deal.roi': 'Cost Ratio (ROI)',
    'deal.profit': 'Net Profit',
    'deal.revenue': 'Revenue',
    'deal.progress': 'Progress',
    'deal.paid': 'Total Paid',
    'deal.performance': 'Performance Analysis',
    'deal.net_sales_desc': 'Total Net Sales',
    'deal.net_profit_desc': '(Net Sales - Cost)',
    'deal.balance': 'Balance (Profit - Paid)',
    'deal.targets': 'Product Targets',
    'deal.source': 'Source (Pharmacies)',
    'deal.no_deals': 'No deals found. Create a new one to start tracking.',
    'deal.select_rep': 'Select Representative',
    'deal.search_prod': 'Search products...',
    'deal.search_pharm': 'Search pharmacies...',
    'deal.qty_box': 'Box',
    'deal.target_help': 'Select products and set target quantity (boxes).',
    'deal.initial_help': 'Initial payment (Commission). Deducted from cash immediately.',
    'deal.target_label': 'Target Products & Quantities',
    'deal.renew': 'Renew Deal',
    'deal.renew_amount': 'Renewal Amount',
    'deal.cycle_history': 'Contract Cycles History',
    'deal.current_cycle': 'Current Cycle',
    'deal.prev_cycle': 'Previous Cycle',
    'deal.evaluation': 'Doctor Evaluation',
    'deal.total_summary': 'Total Summary (All Cycles)',
    'deal.units_vs_target': 'Sold vs Target',
    'set.title': 'Settings',
    'set.language': 'Language',
    'set.currency': 'Currency',
    'set.save': 'Save Changes',
    'set.reset': 'Reset Database',
    'set.tab_general': 'General',
    'set.tab_invoice': 'Invoice Design',
    'set.tab_users': 'Users & Permissions',
    'set.tab_printer': 'Printer Settings',
    'set.paper_size': 'Paper Size',
    'set.paper_a4': 'A4 (Standard)',
    'set.paper_a5': 'A5 (Half)',
    'set.paper_thermal': 'Thermal (Receipt)',
    'set.company_info': 'Company Information',
    'set.company_name': 'Company Name',
    'set.tax_no': 'Tax Number / Reg ID',
    'set.phone': 'Phone Number',
    'set.address': 'Address',
    'set.sys_pref': 'System Preferences',
    'set.select_template': 'Select Invoice Template',
    'user.mgmt_title': 'User Management',
    'user.add': 'Add User',
    'user.edit': 'Edit User',
    'user.fullname': 'Full Name',
    'user.username': 'Username',
    'user.password': 'Password',
    'user.role': 'Role',
    'user.permissions': 'System Permissions',
    'user.save': 'Save User',
    'user.delete_confirm': 'Are you sure you want to delete this user?',
    'role.admin': 'Administrator',
    'role.user': 'User (Employee)',
    'perm.VIEW_DASHBOARD': 'View Dashboard',
    'perm.VIEW_REPORTS': 'View Reports',
    'perm.MANAGE_SALES': 'Manage Sales (Invoices)',
    'perm.MANAGE_INVENTORY': 'Manage Inventory',
    'perm.MANAGE_CUSTOMERS': 'Manage Customers',
    'perm.MANAGE_SUPPLIERS': 'Manage Suppliers',
    'perm.MANAGE_REPS': 'Manage Representatives',
    'perm.MANAGE_WAREHOUSES': 'Manage Warehouses',
    'perm.MANAGE_CASH': 'Cash Register Access',
    'perm.MANAGE_SETTINGS': 'System Settings',
    'perm.MANAGE_USERS': 'Manage Users',
    'inv.add': 'Add Product',
    'inv.customer': 'Customer',
    'inv.supplier': 'Supplier',
    'inv.total': 'Total',
    'inv.subtotal': 'Subtotal',
    'inv.discount': 'Discount',
    'inv.net_total': 'Net Invoice',
    'inv.prev_balance': 'Previous Balance',
    'inv.grand_total': 'Total Due',
    'inv.cash_paid': 'Cash Paid',
    'inv.new_balance': 'New Balance',
    'inv.processing': 'Processing...',
    'inv.finalize': 'Finalize Invoice',
    'inv.update': 'Update Invoice',
    'inv.save_print': 'Save & Print',
    'inv.product': 'Product',
    'inv.batch': 'Batch',
    'inv.qty': 'Qty',
    'inv.bonus': 'Bonus',
    'inv.price': 'Price',
    'inv.action': 'Action',
    'inv.empty_cart': 'Cart is empty',
    'inv.select_customer': 'Select Customer',
    'inv.select_product': 'Select Product',
    'inv.select_batch': 'Select Batch',
    'inv.add_btn': 'Add',
    'inv.insufficient_stock': 'Insufficient Stock',
    'inv.details': 'Invoice Details',
    'inv.select_warehouse': 'Select Warehouse',
    'pur.title': 'New Purchase Invoice',
    'pur.return_title': 'Purchase Return',
    'pur.select_supplier': 'Select Supplier',
    'pur.cost': 'Cost Price',
    'pur.sell': 'Selling Price',
    'pur.batch': 'Batch No',
    'pur.expiry': 'Expiry Date',
    'pur.add_item': 'Add Item',
    'pur.submit': 'Save Purchase',
    'pur.return_submit': 'Save Return',
    'list.title': 'Invoices List',
    'list.search': 'Search...',
    'list.status': 'Status',
    'list.view': 'View',
    'list.edit': 'Edit',
    'list.no_data': 'No data found',
    'common.date': 'Date',
    'common.customer': 'Customer',
    'common.user': 'User',
    'common.status': 'Status',
    'common.action': 'Action',
    'common.success_import': 'Import Successful',
    'common.error_excel': 'Error reading file',
    'common.statement': 'Account Statement',
    'common.debit': 'Debit',
    'common.credit': 'Credit',
    'common.balance': 'Balance',
    'common.desc': 'Description',
    'common.opening': 'Opening Balance',
    'common.print': 'Print',
    'common.landscape': 'Landscape',
    'common.thermal': 'Thermal',
    'common.close': 'Close',
    'status.paid': 'Paid',
    'status.partial': 'Partial',
    'status.unpaid': 'Unpaid',
    'cash.balance': 'Balance',
    // Activity Log
    'log.title': 'Activity Log',
    'log.subtitle': 'Audit trail for security and tracking',
    'log.timestamp': 'Timestamp',
    'log.user': 'User',
    'log.action': 'Action',
    'log.entity': 'Entity',
    'log.details': 'Details',
    'log.all_entities': 'All Entities',
    // Reports
    'rep.period': 'Time Period',
    'rep.from': 'From',
    'rep.to': 'To',
    'rep.apply': 'Apply Filter',
    'rep.today': 'Today',
    'rep.this_month': 'This Month',
    'rep.last_month': 'Last Month',
    'rep.this_year': 'This Year',
    'rep.tab.financial': 'Financial (P&L)',
    'rep.tab.sales': 'Sales Analysis',
    'rep.tab.purchases': 'Purchase Analysis',
    'rep.tab.inventory': 'Inventory Value',
    'rep.tab.partners': 'Partners & Debt',
    'rep.tab.reps': 'Representatives',
    'rep.gross_profit': 'Gross Profit',
    'rep.net_profit': 'Net Profit',
    'rep.total_revenue': 'Total Revenue',
    'rep.cogs': 'Cost of Goods Sold',
    'rep.expenses': 'Operating Expenses',
    'rep.stock_value': 'Stock Asset Value',
    'rep.receivables': 'Receivables (Customers)',
    'rep.payables': 'Payables (Suppliers)',
    'rep.area': 'Area / Region',
    'rep.all_customers': 'All Customers',
    'rep.all_areas': 'All Areas',
    'rep.product_breakdown': 'Product Sales Breakdown',
    'rep.units': 'Units',
    'rep.sales_volume': 'Sales Volume',
    'rep.invoice_count': 'Invoice Count',
    'rep.active_customers': 'Active Customers',
    'rep.commission_est': 'Est. Commission (1%)',
    'rep.select_rep': 'Select Representative',
    'rep.all_reps': 'All Representatives',
    'rep.item_details': 'Item Sales Details'
  },
  ar: {
    // ... existing Arabic translations ...
    'nav.dashboard': 'لوحة التحكم',
    'nav.sales_group': 'المبيعات',
    'nav.new_invoice': 'فاتورة بيع',
    'nav.invoices': 'سجل المبيعات',
    'nav.purchases_group': 'المشتريات',
    'nav.new_purchase': 'فاتورة شراء',
    'nav.purchase_log': 'سجل المشتريات',
    'nav.inventory': 'المخزون',
    'nav.customers': 'العملاء',
    'nav.suppliers': 'الموردين',
    'nav.representatives': 'المندوبين',
    'nav.warehouses': 'المخازن',
    'nav.deals': 'الصفقات',
    'nav.cash': 'الخزينة',
    'nav.settings': 'الإعدادات',
    'nav.reports': 'التقارير والتحليلات',
    'nav.reports_sales': 'تقارير المبيعات',
    'nav.reports_purchases': 'تقارير المشتريات',
    'nav.reports_reps': 'تقارير المندوبين',
    'app.name': 'ميزان أونلاين',
    'app.admin': 'مدير النظام',
    'app.overview': 'نظرة عامة',
    'dash.total_sales': 'إجمالي المبيعات',
    'dash.cash_balance': 'رصيد الخزينة',
    'dash.customers': 'عدد العملاء',
    'dash.low_stock': 'نواقص المخزون',
    'dash.sales_trend': 'مؤشر المبيعات (٧ أيام)',
    'dash.inventory_health': 'حالة المخزون',
    'stock.title': 'إدارة المخزون',
    'stock.import': 'استيراد إكسيل',
    'stock.new': '+ صنف سريع',
    'stock.purchase': 'فاتورة مشتريات',
    'stock.return': 'فاتورة مرتجع',
    'stock.total': 'الرصيد',
    'stock.batch': 'تشغيلة',
    'stock.expiry': 'صلاحية',
    'stock.price': 'سعر بيع',
    'stock.cost': 'تكلفة',
    'stock.qty': 'كمية',
    'stock.active': 'نشط',
    'stock.expired': 'منتهي',
    'stock.warehouse': 'المخزن',
    'stock.transfer': 'تحويل مخزني',
    'stock.transfer_title': 'تحويل بين المخازن',
    'stock.to_warehouse': 'إلى مخزن',
    'stock.transfer_qty': 'الكمية المحولة',
    'ware.title': 'إدارة المخازن',
    'ware.add': 'إضافة مخزن',
    'ware.name': 'اسم المخزن',
    'ware.type': 'النوع',
    'ware.default': 'رئيسي',
    'ware.sub': 'فرعي',
    'cust.title': 'العملاء',
    'cust.add': 'إضافة عميل',
    'cust.search': 'بحث...',
    'cust.code': 'كود',
    'cust.name': 'الاسم',
    'cust.phone': 'هاتف',
    'cust.balance': 'الرصيد',
    'cust.rep': 'المندوب',
    'supp.title': 'الموردين',
    'supp.add': 'إضافة مورد',
    'supp.contact': 'المسئول',
    'rep.title': 'إدارة المندوبين',
    'rep.add': 'إضافة مندوب',
    'rep.code': 'كود المندوب',
    'rep.name': 'اسم المندوب',
    'rep.customers_count': 'عدد العملاء',
    'cash.title': 'دفتر الخزينة',
    'cash.receipt': 'قبض',
    'cash.expense': 'صرف',
    'cash.history': 'السجل',
    'cash.category': 'البند',
    'cash.entity': 'الحساب / الاسم',
    'cash.income': 'إجمالي الوارد',
    'cash.total_expenses': 'إجمالي المصروفات',
    'cash.net': 'الصافي (رصيد)',
    'cat.CUSTOMER_PAYMENT': 'تحصيل من عميل',
    'cat.PARTNER_CONTRIBUTION': 'مساهمة شريك',
    'cat.SUPPLIER_PAYMENT': 'سداد لمورد',
    'cat.SALARY': 'مرتبات',
    'cat.ELECTRICITY': 'كهرباء',
    'cat.MARKETING': 'دعاية وإعلان',
    'cat.DOCTOR_COMMISSION': 'عمولة طبيب (صفقة)',
    'cat.OTHER': 'أخرى',
    'deal.title': 'الصفقات والعمولات',
    'deal.add': 'صفقة جديدة',
    'deal.edit': 'تعديل الصفقة',
    'deal.save': 'حفظ الصفقة',
    'deal.update': 'تحديث الصفقة',
    'deal.doctor': 'اسم الطبيب',
    'deal.linked_cust': 'الصيدليات المرتبطة',
    'deal.pay_comm': 'صرف عمولة',
    'deal.sales_vol': 'حجم التعاملات',
    'deal.select_cust': 'اختر العملاء',
    'deal.amount': 'مبلغ العمولة / مقدم (اختياري)',
    'deal.roi': 'نسبة التكلفة (ROI)',
    'deal.profit': 'صافي الربح',
    'deal.revenue': 'المبيعات',
    'deal.progress': 'الإنجاز',
    'deal.paid': 'إجمالي المدفوع',
    'deal.performance': 'تحليل الأداء',
    'deal.net_sales_desc': 'صافي المبيعات (منذ البداية)',
    'deal.net_profit_desc': '(صافي البيع - تكلفة البضاعة)',
    'deal.balance': 'الرصيد (الربح - المدفوع)',
    'deal.targets': 'مستهدفات الأصناف',
    'deal.source': 'المصدر (الصيدليات)',
    'deal.no_deals': 'لا توجد صفقات حالياً. أضف صفقة جديدة لبدء التتبع.',
    'deal.select_rep': 'اختر المندوب',
    'deal.search_prod': 'بحث عن صنف...',
    'deal.search_pharm': 'بحث عن صيدلية...',
    'deal.qty_box': 'علبة',
    'deal.target_help': 'حدد الأصناف والكمية المستهدفة (بالعلبة).',
    'deal.initial_help': 'دفعة مقدمة (عمولة). تخصم من الخزينة فوراً.',
    'deal.target_label': 'الأصناف المستهدفة والكميات',
    'deal.renew': 'تجديد الصفقة',
    'deal.renew_amount': 'مبلغ التجديد (عمولة جديدة)',
    'deal.cycle_history': 'سجل العقود (الدورات)',
    'deal.current_cycle': 'العقد الحالي',
    'deal.prev_cycle': 'عقد سابق',
    'deal.evaluation': 'تقييم الطبيب',
    'deal.total_summary': 'الملخص الشامل (كل الدورات)',
    'deal.units_vs_target': 'مباع / مستهدف',
    'set.title': 'الإعدادات',
    'set.language': 'اللغة',
    'set.currency': 'العملة',
    'set.save': 'حفظ التغييرات',
    'set.reset': 'حذف البيانات',
    'set.tab_general': 'عام',
    'set.tab_invoice': 'تصميم الفاتورة',
    'set.tab_users': 'المستخدمين والصلاحيات',
    'set.tab_printer': 'إعدادات الطباعة',
    'set.paper_size': 'حجم الورق',
    'set.paper_a4': 'A4 (قياسي)',
    'set.paper_a5': 'A5 (نصف ورقة)',
    'set.paper_thermal': 'طابعة إيصالات (80mm)',
    'set.company_info': 'بيانات الشركة',
    'set.company_name': 'اسم الشركة',
    'set.tax_no': 'رقم ضريبي / سجل',
    'set.phone': 'رقم الهاتف',
    'set.address': 'العنوان',
    'set.sys_pref': 'تفضيلات النظام',
    'set.select_template': 'اختر شكل الفاتورة',
    'user.mgmt_title': 'إدارة المستخدمين',
    'user.add': 'إضافة مستخدم',
    'user.edit': 'تعديل المستخدم',
    'user.fullname': 'الاسم بالكامل',
    'user.username': 'اسم المستخدم',
    'user.password': 'كلمة المرور',
    'user.role': 'الدور الوظيفي',
    'user.permissions': 'صلاحيات النظام',
    'user.save': 'حفظ المستخدم',
    'user.delete_confirm': 'هل أنت متأكد من حذف هذا المستخدم؟',
    'role.admin': 'مدير (كامل الصلاحيات)',
    'role.user': 'مستخدم (موظف)',
    'perm.VIEW_DASHBOARD': 'عرض لوحة التحكم',
    'perm.VIEW_REPORTS': 'عرض التقارير',
    'perm.MANAGE_SALES': 'إدارة المبيعات',
    'perm.MANAGE_INVENTORY': 'إدارة المخزون',
    'perm.MANAGE_CUSTOMERS': 'إدارة العملاء',
    'perm.MANAGE_SUPPLIERS': 'إدارة الموردين',
    'perm.MANAGE_REPS': 'إدارة المندوبين',
    'perm.MANAGE_WAREHOUSES': 'إدارة المخازن',
    'perm.MANAGE_CASH': 'إدارة الخزينة',
    'perm.MANAGE_SETTINGS': 'إعدادات النظام',
    'perm.MANAGE_USERS': 'إدارة المستخدمين',
    'inv.add': 'إضافة صنف',
    'inv.customer': 'العميل',
    'inv.supplier': 'المورد',
    'inv.total': 'الإجمالي',
    'inv.subtotal': 'المجموع الفرعي',
    'inv.discount': 'الخصم',
    'inv.net_total': 'صافي الفاتورة',
    'inv.prev_balance': 'الحساب السابق',
    'inv.grand_total': 'إجمالي المستحق',
    'inv.cash_paid': 'المدفوع',
    'inv.new_balance': 'الرصيد الجديد',
    'inv.processing': 'جاري الحفظ...',
    'inv.finalize': 'حفظ الفاتورة',
    'inv.update': 'تعديل الفاتورة',
    'inv.save_print': 'حفظ وطباعة',
    'inv.product': 'الصنف',
    'inv.batch': 'التشغيلة',
    'inv.qty': 'الكمية',
    'inv.bonus': 'بونص',
    'inv.price': 'السعر',
    'inv.action': 'إجراء',
    'inv.empty_cart': 'الفاتورة فارغة',
    'inv.select_customer': 'اختر العميل',
    'inv.select_product': 'اختر الصنف',
    'inv.select_batch': 'اختر التشغيلة',
    'inv.add_btn': 'إضافة',
    'inv.insufficient_stock': 'الرصيد لا يسمح',
    'inv.details': 'تفاصيل الفاتورة',
    'inv.select_warehouse': 'اختر المخزن',
    'pur.title': 'فاتورة مشتريات جديدة',
    'pur.return_title': 'فاتورة مرتجع مشتريات',
    'pur.select_supplier': 'اختر المورد',
    'pur.cost': 'سعر الشراء',
    'pur.sell': 'سعر البيع',
    'pur.batch': 'رقم التشغيلة',
    'pur.expiry': 'تاريخ الصلاحية',
    'pur.add_item': 'إضافة للفاتورة',
    'pur.submit': 'حفظ المشتريات',
    'pur.return_submit': 'حفظ المرتجع',
    'list.title': 'سجل الفواتير',
    'list.search': 'بحث...',
    'list.status': 'الحالة',
    'list.view': 'عرض',
    'list.edit': 'تعديل',
    'list.no_data': 'لا توجد بيانات',
    'common.date': 'التاريخ',
    'common.customer': 'العميل',
    'common.user': 'المستخدم',
    'common.status': 'الحالة',
    'common.action': 'إجراء',
    'common.success_import': 'تم الاستيراد بنجاح',
    'common.error_excel': 'خطأ في قراءة الملف',
    'common.statement': 'كشف حساب',
    'common.debit': 'مدين',
    'common.credit': 'دائن',
    'common.balance': 'الرصيد',
    'common.desc': 'البيان',
    'common.opening': 'رصيد افتتاحي',
    'common.print': 'طباعة',
    'common.landscape': 'عرضي (A4)',
    'common.thermal': 'حراري (ايصال)',
    'common.close': 'إغلاق',
    'status.paid': 'خالص',
    'status.partial': 'جزئي',
    'status.unpaid': 'آجل',
    'cash.balance': 'الرصيد الحالي',
    // Activity Log
    'log.title': 'سجل النشاط',
    'log.subtitle': 'سجل الرقابة وتتبع الحركات',
    'log.timestamp': 'التوقيت',
    'log.user': 'المستخدم',
    'log.action': 'الإجراء',
    'log.entity': 'العنصر',
    'log.details': 'التفاصيل',
    'log.all_entities': 'كل العناصر',
    // Reports
    'rep.period': 'الفترة الزمنية',
    'rep.from': 'من تاريخ',
    'rep.to': 'إلى تاريخ',
    'rep.apply': 'تطبيق الفلتر',
    'rep.today': 'اليوم',
    'rep.this_month': 'هذا الشهر',
    'rep.last_month': 'الشهر السابق',
    'rep.this_year': 'هذا العام',
    'rep.tab.financial': 'القوائم المالية (أرباح وخسائر)',
    'rep.tab.sales': 'تحليل المبيعات',
    'rep.tab.purchases': 'تحليل المشتريات',
    'rep.tab.inventory': 'تقييم المخزون',
    'rep.tab.partners': 'الشركاء والمديونيات',
    'rep.tab.reps': 'أداء المندوبين',
    'rep.gross_profit': 'مجمل الربح',
    'rep.net_profit': 'صافي الربح',
    'rep.total_revenue': 'إجمالي الإيرادات',
    'rep.cogs': 'تكلفة البضاعة المباعة',
    'rep.expenses': 'المصروفات التشغيلية',
    'rep.stock_value': 'قيمة الأصول المخزنية',
    'rep.receivables': 'العملاء (مدينون)',
    'rep.payables': 'الموردين (دائنون)',
    'rep.area': 'المنطقة / الحي',
    'rep.all_customers': 'كل العملاء',
    'rep.all_areas': 'كل المناطق',
    'rep.product_breakdown': 'تفاصيل مبيعات الأصناف',
    'rep.units': 'وحدة',
    'rep.sales_volume': 'حجم المبيعات',
    'rep.invoice_count': 'عدد الفواتير',
    'rep.active_customers': 'العملاء النشطون',
    'rep.commission_est': 'عمولة تقديرية (١٪)',
    'rep.select_rep': 'اختر المندوب',
    'rep.all_reps': 'كل المندوبين',
    'rep.item_details': 'تفاصيل الأصناف المباعة'
  }
};

export const t = (key: string): string => {
  // Use cached settings if available in localStorage to prevent async flicker on UI texts
  const saved = localStorage.getItem('settings');
  const lang = saved ? JSON.parse(saved).language : 'ar';
  
  return translations[lang === 'ar' ? 'ar' : 'en'][key] || key;
};

export const isRTL = (): boolean => {
  const saved = localStorage.getItem('settings');
  const lang = saved ? JSON.parse(saved).language : 'ar';
  return lang === 'ar';
};
